### ISSUE TITLE
Roadmap Sezione Cassa

### ISSUE THREAD

**Issue by AngeloDotNet** [AepServerNet/GestioneSagre#5]
Sezione CASSA
- [ ] Nuovo scontrino
- [ ] Ristampa scontrino
- [ ] Cambia stato scontrino
- [ ] Cambia tipo scontrino
- [ ] Cambia tipo pagamento
- [ ] Gestione prenotazioni
- [ ] Movimenti cassa
