### ISSUE TITLE
Roadmap Sezione Report

### ISSUE THREAD

**Issue by AngeloDotNet** [AepServerNet/GestioneSagre#7]
Sezione REPORT
- [ ] Stampa prenotazioni
- [ ] Stampa menu
- [ ] Stampa contabilità cassa
- [ ] Stampa consumi giornata
- [ ] Stampa consumi totali
- [ ] Stampa riepilogo cassa
- [ ] Stampa riepilogo incassi
